@url_dev = http://localhost:3056/v1/api


POST {{url_dev}}/shop/signup
Content-Type: application/json

{
    "name" : "Nguyen Trung Anh",
    "email": "trunganh10@gmail.com",
    "password":"anh123"
}